# Copyright (c) 2026 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: e05c5c0818279e5ac248ac9e954431ba58865e61  # frozen: v0.15.7
  hooks:
  - id: ruff-check
    name: "ruff check"
    args: ["--extend-select", "I", "--fix"]
  - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
  hooks:
  - id: codespell
    exclude: >
        (?x)^(
            .*Cargo\.toml$
        )$

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 88c364bab316f4b6b18f6c298133bbbf32d7cd15  # frozen: v22.1.1
  hooks:
  - id: clang-format
    types_or: [c, c++]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
    args: ["--enforce-all"]
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: '\.sln$'
  - id: mixed-line-ending
    args: [--fix=lf]
    exclude: '\.(bat|sln)$'
  - id: trailing-whitespace

- repo: https://github.com/adbc-drivers/dev
  rev: ffdbb1a1237b89cafb15a7420667f54838986681
  hooks:
  - id: rat

- repo: local
  hooks:
  - id: cargo fmt
    name: cargo fmt
    language: system
    types: [rust]
    entry: bash -c 'cd rust && cargo +stable fmt --all'
    pass_filenames: false
